enum SignupErrorCode {
  DUPLICATE_EMAIL = "DUPLICATE_EMAIL",
  INVALID_EMAIL = "INVALID_EMAIL",
  DUPLICATE_USERNAME = "DUPLICATE_USERNAME",
  WEAK_PASSWORD = "WEAK_PASSWORD",
}

export default SignupErrorCode;
